function plot_best_model_dots(AIC_mat, BIC_mat, modelNames, outPDF_ab)

K = size(AIC_mat, 1);
nModels = numel(modelNames);

[~, bestAIC_idx] = min(AIC_mat, [], 2, 'omitnan');
[~, bestBIC_idx] = min(BIC_mat, [], 2, 'omitnan');

allNanAIC = all(isnan(AIC_mat), 2);
allNanBIC = all(isnan(BIC_mat), 2);

bestAIC_idx(allNanAIC) = NaN;
bestBIC_idx(allNanBIC) = NaN;

figAB = figure('Color','w','Position',[180 160 1000 420]); hold on;

yModel = 1:nModels;

hAIC = plot(nan, nan, 'o', ...
    'MarkerSize', 5, ...
    'MarkerFaceColor', [0 0.4470 0.7410], ...
    'MarkerEdgeColor', 'none', ...
    'DisplayName', 'Min AIC');

hBIC = plot(nan, nan, 'o', ...
    'MarkerSize', 5, ...
    'MarkerFaceColor', [0.8500 0.3250 0.0980], ...
    'MarkerEdgeColor', 'none', ...
    'DisplayName', 'Min BIC');

for k = 1:K
    if ~isnan(bestAIC_idx(k))
        plot(k, bestAIC_idx(k)-0.10, 'o', ...
            'MarkerSize', 5, ...
            'MarkerFaceColor', [0 0.4470 0.7410], ...
            'MarkerEdgeColor', 'none', ...
            'HandleVisibility', 'off');
    end
end

for k = 1:K
    if ~isnan(bestBIC_idx(k))
        plot(k, bestBIC_idx(k)+0.10, 'o', ...
            'MarkerSize', 5, ...
            'MarkerFaceColor', [0.8500 0.3250 0.0980], ...
            'MarkerEdgeColor', 'none', ...
            'HandleVisibility', 'off');
    end
end

set(gca, ...
    'YTick', yModel, ...
    'YTickLabel', modelNames, ...
    'YLim', [0.5 nModels+0.5], ...
    'XTick', 1:K, ...
    'XLim', [0.5 K+0.5], ...
    'FontSize', 11, ...
    'LineWidth', 1, ...
    'TickLabelInterpreter','none');

xlabel('Time bin');
ylabel('Model');
title('Best model per time bin: AIC (blue) and BIC (red)', 'Interpreter','none');

grid on;
box off;

legend([hAIC, hBIC], {'Min AIC','Min BIC'}, 'Location','eastoutside');

set(figAB,'Renderer','painters');
print(figAB, outPDF_ab, '-dpdf', '-painters');
fprintf('✓ Saved AIC/BIC dot plot: %s\n', outPDF_ab);

end